# Generated by Django 2.2.7 on 2019-11-23 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0002_instagrampost_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manytomany.InstagramPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manytomany.InstagramUser')),
            ],
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='like_users',
            field=models.ManyToManyField(blank=True, through='manytomany.InstagramPostLike', to='manytomany.InstagramUser'),
        ),
    ]
