# Generated by Django 2.2.7 on 2019-11-23 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0003_auto_20191123_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampostlike',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 8, 54, 25, 768139, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('friends', models.ManyToManyField(blank=True, related_name='_facebookuser_friends_+', to='manytomany.FacebookUser')),
            ],
        ),
    ]
