# Generated by Django 2.2.7 on 2019-11-23 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0004_auto_20191123_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampostlike',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 8, 58, 39, 511035, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('following', models.ManyToManyField(blank=True, to='manytomany.TwitterUser')),
            ],
        ),
    ]
